Deleting this branch, since I only made it to assist in testing the compilation errors.
git-tfs-id: [http://ros-tfs-px01.picis.com:8080/tfs/emar]$/;C43